/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaGUI;
import CapaNegocio.NegocioMenu;
import CapaDTO.Empleado;
import javax.swing.JOptionPane;

/**
 *
 * @author Cesar
 */
public class VistaMenu extends javax.swing.JFrame {
    /*Centrado 
    public VistaMenu(){
        initComponents();
        this.setLocationRelativeTo(null);
    }
    */
    public void validarTrabajador (){
        Empleado emp = new Empleado();
        NegocioMenu menu = new NegocioMenu();
        String rut = txt_rut.getText();
        if(!"".equals(rut)){
            emp = menu.emp(rut);
            if (emp.getRut_empleado()!= null){
                VistaTrabajador pMenu = new VistaTrabajador();
                pMenu.setVisible(true);
                dispose();
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Rut incorrecto");
        }
        }
        
    }
    /**
     * Creates new form VistaMenu
     */
    public VistaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();
        jLabelBienvenido = new javax.swing.JLabel();
        txt_rut = new javax.swing.JTextField();
        jLabelRut = new javax.swing.JLabel();
        bto_ingresar = new javax.swing.JButton();
        bto_salir = new javax.swing.JButton();
        jPanelNaranja = new javax.swing.JPanel();
        jLabelFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/IconPeque.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, -1, -1));

        jLabelBienvenido.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelBienvenido.setText("¡Bienvenido!");
        getContentPane().add(jLabelBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, -1, -1));

        txt_rut.setToolTipText("");
        txt_rut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rutActionPerformed(evt);
            }
        });
        getContentPane().add(txt_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, 107, -1));

        jLabelRut.setText("Rut");
        jLabelRut.setMaximumSize(new java.awt.Dimension(34, 14));
        jLabelRut.setMinimumSize(new java.awt.Dimension(34, 14));
        jLabelRut.setPreferredSize(new java.awt.Dimension(34, 14));
        getContentPane().add(jLabelRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, -1, -1));

        bto_ingresar.setText("Ingresar");
        bto_ingresar.setMaximumSize(new java.awt.Dimension(80, 23));
        bto_ingresar.setPreferredSize(new java.awt.Dimension(100, 23));
        bto_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_ingresarActionPerformed(evt);
            }
        });
        getContentPane().add(bto_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, -1, -1));

        bto_salir.setText("Salir");
        bto_salir.setPreferredSize(new java.awt.Dimension(70, 23));
        bto_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_salirActionPerformed(evt);
            }
        });
        getContentPane().add(bto_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 400, -1, -1));

        jPanelNaranja.setBackground(new java.awt.Color(255, 153, 102));
        getContentPane().add(jPanelNaranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 330, 720));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/FondoGrande.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-500, -60, 1470, 780));
        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bto_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_ingresarActionPerformed
        // TODO add your handling code here:
       // validarTrabajador();
       VistaTrabajador pMenu = new VistaTrabajador();
                pMenu.setVisible(true);
                dispose();
    }//GEN-LAST:event_bto_ingresarActionPerformed

    private void bto_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.gc();
    }//GEN-LAST:event_bto_salirActionPerformed

    private void txt_rutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rutActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bto_ingresar;
    private javax.swing.JButton bto_salir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelBienvenido;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelRut;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelNaranja;
    private javax.swing.JTextField txt_rut;
    // End of variables declaration//GEN-END:variables
 }    
