/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaGUI;

/**
 *
 * @author Cesar
 */
public class VistaTrabajador extends javax.swing.JFrame {

    /**
     * Creates new form VistaTrabajador
     */
    public VistaTrabajador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bto_venta = new javax.swing.JButton();
        bto_cerrarSesion = new javax.swing.JButton();
        bto_cancelar = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bto_venta.setText("Venta");
        bto_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_ventaActionPerformed(evt);
            }
        });
        getContentPane().add(bto_venta);
        bto_venta.setBounds(100, 170, 65, 25);

        bto_cerrarSesion.setText("Cerrar Sesion");
        getContentPane().add(bto_cerrarSesion);
        bto_cerrarSesion.setBounds(280, 20, 111, 25);

        bto_cancelar.setText("Cancelar Venta");
        getContentPane().add(bto_cancelar);
        bto_cancelar.setBounds(210, 170, 119, 25);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/IconMini.png"))); // NOI18N
        getContentPane().add(jLabelLogo);
        jLabelLogo.setBounds(0, 0, 80, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bto_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_ventaActionPerformed
        // TODO add your handling code here:
        VistaVenta pMenu = new VistaVenta();
        pMenu.setVisible(true);
    }//GEN-LAST:event_bto_ventaActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bto_cancelar;
    private javax.swing.JButton bto_cerrarSesion;
    private javax.swing.JButton bto_venta;
    private javax.swing.JLabel jLabelLogo;
    // End of variables declaration//GEN-END:variables
}
