/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaGUI;

import CapaDTO.Producto;
import CapaNegocio.NegocioProducto;
import CapaNegocio.NegocioVenta;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cesar
 */
public class VistaVenta extends javax.swing.JFrame {
    
    
    
    
    /**
     * Creates new form VistaVenta
     */
    public VistaVenta() {
        initComponents();
    }
    
    PreparedStatement ps;
    ResultSet rs;
    
    
    public void buscarProducto()
    {
        
        Connection con1 = null;
        try{
            NegocioProducto auxNegocioProducto = new NegocioProducto();
            con1 = (Connection) auxNegocioProducto.getConect1();
            ps = con1.prepareStatement("SELECT FROM producto where id_producto = ?");
            ps.setString(1,txt_idProducto.getText());
            
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                txt_nombreProducto.setText(rs.getString("nombre_producto"));
                txt_precioUnitario.setText(rs.getString("precio_unitario"));
            }
            
        } catch(Exception e){
                System.err.println(e);}
    }
    
    
    public void agregarTablaProducto () {
        try{
        DefaultTableModel modelo = new DefaultTableModel();
            modelo = (DefaultTableModel) this.table_venta.getModel();
            modelo.setNumRows(0);
            NegocioProducto auxNegocioProducto = new NegocioProducto();
            Iterator iter = auxNegocioProducto.consultarProducto().iterator();
            int fila = 0;
            while(iter.hasNext())
            {
                Producto auxProducto = new Producto();
                auxProducto = (Producto) iter.next();
                Object[] num = {};
                modelo.addRow(num);
                this.table_venta.setValueAt(auxProducto.getIdProducto(), fila, 0);
                this.table_venta.setValueAt(auxProducto.getNombreProducto(), fila, 1);
                this.table_venta.setValueAt(this.txt_cantidad, fila, 2);
                this.table_venta.setValueAt((Integer.parseInt(this.txt_cantidad.getText()) * auxProducto.getPrecioUnitario()), fila, 3);
                fila++;
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"No se ha podido listar a los jugadores " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_idProducto = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_nombreProducto = new javax.swing.JTextField();
        txt_precioUnitario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_venta = new javax.swing.JTable();
        bto_agregar = new javax.swing.JButton();
        bto_continuar = new javax.swing.JButton();
        bto_salir = new javax.swing.JButton();
        bto_cancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_precioFinal = new javax.swing.JTextField();
        jLabelLogo = new javax.swing.JLabel();
        bto_buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("ID Producto");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 150, 57, 14);

        jLabel2.setText("Cantidad");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 180, 43, 14);

        jLabel3.setText("Precio Unitario");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 240, 69, 14);

        txt_idProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idProductoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_idProducto);
        txt_idProducto.setBounds(170, 150, 178, 20);

        txt_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidadActionPerformed(evt);
            }
        });
        getContentPane().add(txt_cantidad);
        txt_cantidad.setBounds(170, 180, 178, 20);

        jLabel6.setText("Nombre Producto");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 210, 83, 14);

        txt_nombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreProductoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nombreProducto);
        txt_nombreProducto.setBounds(170, 210, 178, 20);

        txt_precioUnitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_precioUnitarioActionPerformed(evt);
            }
        });
        getContentPane().add(txt_precioUnitario);
        txt_precioUnitario.setBounds(170, 240, 178, 20);

        table_venta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID producto", "Nombre Producto", "Cantidad", "Precio Unitario ", "Precio Total"
            }
        ));
        jScrollPane1.setViewportView(table_venta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(430, 150, 450, 140);

        bto_agregar.setText("Agregar");
        bto_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(bto_agregar);
        bto_agregar.setBounds(160, 310, 71, 23);

        bto_continuar.setText("Continuar");
        getContentPane().add(bto_continuar);
        bto_continuar.setBounds(731, 468, 79, 23);

        bto_salir.setText("Salir");
        bto_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_salirActionPerformed(evt);
            }
        });
        getContentPane().add(bto_salir);
        bto_salir.setBounds(840, 470, 53, 23);

        bto_cancelar.setText("Cancelar");
        getContentPane().add(bto_cancelar);
        bto_cancelar.setBounds(270, 310, 75, 23);

        jLabel4.setText("Precio Final");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(463, 405, 54, 14);
        getContentPane().add(txt_precioFinal);
        txt_precioFinal.setBounds(570, 402, 100, 20);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/IconMini.png"))); // NOI18N
        getContentPane().add(jLabelLogo);
        jLabelLogo.setBounds(0, -10, 110, 110);

        bto_buscar.setText("Buscar");
        bto_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(bto_buscar);
        bto_buscar.setBounds(40, 310, 73, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idProductoActionPerformed

    private void txt_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidadActionPerformed

    private void txt_nombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreProductoActionPerformed

    private void txt_precioUnitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precioUnitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precioUnitarioActionPerformed

    private void bto_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_agregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bto_agregarActionPerformed

    private void bto_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_salirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bto_salirActionPerformed

    private void bto_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_buscarActionPerformed
        // TODO add your handling code here:
        
        buscarProducto();
    }//GEN-LAST:event_bto_buscarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bto_agregar;
    private javax.swing.JButton bto_buscar;
    private javax.swing.JButton bto_cancelar;
    private javax.swing.JButton bto_continuar;
    private javax.swing.JButton bto_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_venta;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_idProducto;
    private javax.swing.JTextField txt_nombreProducto;
    private javax.swing.JTextField txt_precioFinal;
    private javax.swing.JTextField txt_precioUnitario;
    // End of variables declaration//GEN-END:variables
}
