/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaGUI;

/**
 *
 * @author Cesar
 */
public class VistaTrabajador extends javax.swing.JFrame {

    /**
     * Creates new form VistaTrabajador
     */
    public VistaTrabajador() {
        initComponents();
        VistaMenu pMenu = new VistaMenu();
        lbl_rutTrabajador.setText(pMenu.rut_empleado);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bto_venta = new javax.swing.JButton();
        bto_cerrarSesion = new javax.swing.JButton();
        bto_cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_rutTrabajador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 560));
        getContentPane().setLayout(null);

        bto_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/compras.png"))); // NOI18N
        bto_venta.setText("Venta");
        bto_venta.setPreferredSize(new java.awt.Dimension(75, 23));
        bto_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_ventaActionPerformed(evt);
            }
        });
        getContentPane().add(bto_venta);
        bto_venta.setBounds(280, 310, 140, 50);

        bto_cerrarSesion.setText("Cerrar Sesion");
        bto_cerrarSesion.setPreferredSize(new java.awt.Dimension(150, 23));
        bto_cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_cerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(bto_cerrarSesion);
        bto_cerrarSesion.setBounds(220, 60, 150, 23);

        bto_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/eliminar.png"))); // NOI18N
        bto_cancelar.setText("Cancelar Venta");
        bto_cancelar.setPreferredSize(new java.awt.Dimension(125, 23));
        bto_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(bto_cancelar);
        bto_cancelar.setBounds(490, 310, 170, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/banner.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 980, 140);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Rut Trabajador");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 190, 130, 50);

        lbl_rutTrabajador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_rutTrabajador);
        lbl_rutTrabajador.setBounds(190, 200, 130, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bto_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_ventaActionPerformed
        // TODO add your handling code here:
        VistaDetalleVenta pMenu = new VistaDetalleVenta();
        pMenu.setVisible(true);
    }//GEN-LAST:event_bto_ventaActionPerformed

    private void bto_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_cancelarActionPerformed
        // TODO add your handling code here:
        VistaCancelarVenta pMenu = new VistaCancelarVenta();
        pMenu.setVisible(true);
        
    }//GEN-LAST:event_bto_cancelarActionPerformed

    private void bto_cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_cerrarSesionActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.gc();
        VistaMenu pMenu = new VistaMenu();
        pMenu.setVisible(true);
        
    }//GEN-LAST:event_bto_cerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bto_cancelar;
    private javax.swing.JButton bto_cerrarSesion;
    private javax.swing.JButton bto_venta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_rutTrabajador;
    // End of variables declaration//GEN-END:variables
}
